### ISSUE TITLE
Installing spine_aws_common from repo url fails due to bad VERSION in setup.cfg

### ISSUE THREAD

**Issue by jamesnunn** [NHSDigital/spine-core-aws-common#19]
Having added this to our requirements.txt file and running `pip install .` the WARNING and  ERROR in the output below hints at a bad config. I forked the repo, changed setup.cfg line 3 from `version = VERSION` to `version = 0.0.3` and rereleased v0.0.3 and it installed fine.

requirements.txt:
```
spine_aws_common @ git+https://github.com/NHSDigital/spine-core-aws-common@v0.0.3
```

Command: 
```
pip install .
```

Output:
```Building wheels for collected packages: spine-aws-common, retrying, future, wrapt
  Building wheel for spine-aws-common (PEP 517) ... done
  Created wheel for spine-aws-common: filename=spine_aws_common-VERSION-py3-none-any.whl size=27508 sha256=1732e841e12cf5dc9d0f3f73f5645a00f91d8793a9b7fc4e66179edbf91ec4d4
  Stored in directory: /tmp/pip-ephem-wheel-cache-td8rf31g/wheels/36/d1/55/740f4265f06c94b35a81c6a2c2eea0382c189cfffd51400277
  **WARNING: Built wheel for spine-aws-common is invalid: Metadata 1.2 mandates PEP 440 version, but 'VERSION' is not**
  Building wheel for retrying (setup.py) ... done
  Created wheel for retrying: filename=retrying-1.3.3-py3-none-any.whl size=11448 sha256=3b761dcab22b255db782f465f520117d85b15f0bf1419a5176525b364dfd6d92
  Stored in directory: /tmp/pip-ephem-wheel-cache-td8rf31g/wheels/ce/18/7f/e9527e3e66db1456194ac7f61eb3211068c409edceecff2d31
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491070 sha256=c5534b4820287a88ea47aa693831a7cc301d70ea30e4417200e905a951fdb1da
  Stored in directory: /tmp/pip-ephem-wheel-cache-td8rf31g/wheels/2f/a0/d3/4030d9f80e6b3be787f19fc911b8e7aa462986a40ab1e4bb94
  Building wheel for wrapt (setup.py) ... done
  Created wheel for wrapt: filename=wrapt-1.12.1-cp39-cp39-linux_x86_64.whl size=72038 sha256=2a1291708ca44ab456a5ae9bdfeeb70cd88692172aeb3ef4503b6d0e050389fc
  Stored in directory: /tmp/pip-ephem-wheel-cache-td8rf31g/wheels/98/23/68/efe259aaca055e93b08e74fbe512819c69a2155c11ba3c0f10
Successfully built retrying future wrapt
Failed to build spine-aws-common
**ERROR: Could not build wheels for spine-aws-common which use PEP 517 and cannot be installed directly**```

**Comment by c-turner** [comment]
Is there reason you can't specify your requirements.txt in the way demonstrated in the README?
```
https://github.com/NHSDigital/spine-core-aws-common/releases/download/v0.0.3/spine_aws_common-0.0.3-py3-none-any.whl
```

As the wheel is already provided, you shouldn't need to rebuild the package. The config is set as such that the version is currently set when a Github action creates the release.

**Comment by aparimoo-nhs** [comment]
it breaks` setup.py` dependencies

` 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Parse error at "'://githu'": Expected stringEnd`

**Comment by jamesnunn** [comment]
If you have already successfully installed this using the link to the wheel and using setuptools to install dependencies I'd be glad to see how you made it work.

**Comment by c-turner** [comment]
Have you tried passing the following into install_requires instead?
```spine_aws_common@https://github.com/NHSDigital/spine-core-aws-common/releases/download/v0.0.3/spine_aws_common-0.0.3-py3-none-any.whl```

**Comment by ben-clarke** [comment]
`spine-aws-common @ https://github.com/NHSDigital/spine-core-aws-common/releases/download/v0.0.3/spine_aws_common-0.0.3-py3-none-any.whl` works for me. This is what gets generated by poetry when doing an export.

**Comment by aparimoo-nhs** [comment]
> `spine-aws-common @ https://github.com/NHSDigital/spine-core-aws-common/releases/download/v0.0.3/spine_aws_common-0.0.3-py3-none-any.whl` works for me. This is what gets generated by poetry when doing an export.

This is working. Thanks @ben-clarke
